version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build-and-test:
    working_directory: ~/selenium-with-testng
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/node:17.1.0
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn clean test -DsuiteXmlFile=testng.xml -Dbrowser=chrome

workflows:
  sample:
    jobs:
      - build-and-test